In [4]:
import numpy as np
import pandas as pd

In [5]:
# Using encoding = "ISO-8859-1"
hospitals_infections = pd.read_csv("Healthcare_Associated_Infections_Hospital.csv", encoding = "ISO-8859-1")
hospitals_infections.head()

,Provider ID,Hospital Name,Address,City,State,ZIP Code,County Name,Phone Number,Measure Name,Measure ID,Compared to National,Score,Footnote,Measure Start Date,Measure End Date
0,10001,SOUTHEAST ALABAMA MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,HOUSTON,3347938701,CLABSI: Lower Confidence Limit,HAI_1_CI_LOWER,NaN,1.03,NaN,1/1/2015,12/31/2015
1,10001,SOUTHEAST ALABAMA MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,HOUSTON,3347938701,CLABSI: Upper Confidence Limit,HAI_1_CI_UPPER,NaN,2.765,NaN,1/1/2015,12/31/2015
2,10001,SOUTHEAST ALABAMA MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,HOUSTON,3347938701,CLABSI: Number of Device Days,HAI_1_DOPC_DAYS,NaN,7117,NaN,1/1/2015,12/31/2015
3,10001,SOUTHEAST ALABAMA MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,HOUSTON,3347938701,CLABSI: Predicted Cases,HAI_1_ELIGCASES,NaN,9.198,NaN,1/1/2015,12/31/2015
4,10001,SOUTHEAST ALABAMA MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,HOUSTON,3347938701,CLABSI: Observed Cases,HAI_1_NUMERATOR,NaN,16,NaN,1/1/2015,12/31/2015

In [6]:
outpatient_imaging = pd.read_csv("Outpatient Imaging Efficiency - Hospital.csv")
outpatient_imaging.head()

,Provider ID,Hospital Name,Address,City,State,ZIP Code,County Name,Phone Number,Measure ID,Measure Name,Score,Footnote,Measure Start Date,Measure End Date
0,10001,SOUTHEAST ALABAMA MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,HOUSTON,3347938701,OP_10,Abdomen CT Use of Contrast Material,6.4,NaN,07/01/2014,06/30/2015
1,10001,SOUTHEAST ALABAMA MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,HOUSTON,3347938701,OP_11,Thorax CT Use of Contrast Material,0.9,NaN,07/01/2014,06/30/2015
2,10001,SOUTHEAST ALABAMA MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,HOUSTON,3347938701,OP_13,Outpatients who got cardiac imaging stress tes...,7.1,NaN,07/01/2014,06/30/2015
3,10001,SOUTHEAST ALABAMA MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,HOUSTON,3347938701,OP_14,Outpatients with brain CT scans who got a sinu...,2.4,NaN,07/01/2014,06/30/2015
4,10001,SOUTHEAST ALABAMA MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,HOUSTON,3347938701,OP_8,MRI Lumbar Spine for Low Back Pain,38.1,NaN,07/01/2014,06/30/2015

In [7]:
readmission = pd.read_csv("Readmissions and Deaths - Hospital.csv")
readmission.head()

,Provider ID,Hospital Name,Address,City,State,ZIP Code,County Name,Phone Number,Measure Name,Measure ID,Compared to National,Denominator,Score,Lower Estimate,Higher Estimate,Footnote,Measure Start Date,Measure End Date
0,10001,SOUTHEAST ALABAMA MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,HOUSTON,3347938701,Acute Myocardial Infarction (AMI) 30-Day Morta...,MORT_30_AMI,No Different than the National Rate,733,12.5,10.6,14.9,NaN,07/01/2012,06/30/2015
1,10001,SOUTHEAST ALABAMA MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,HOUSTON,3347938701,Death rate for CABG,MORT_30_CABG,No Different than the National Rate,278,4.2,2.6,6.8,NaN,07/01/2012,06/30/2015
2,10001,SOUTHEAST ALABAMA MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,HOUSTON,3347938701,Death rate for chronic obstructive pulmonary d...,MORT_30_COPD,No Different than the National Rate,586,9.3,7.3,11.8,NaN,07/01/2012,06/30/2015
3,10001,SOUTHEAST ALABAMA MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,HOUSTON,3347938701,Heart failure (HF) 30-Day Mortality Rate,MORT_30_HF,No Different than the National Rate,797,12.4,10.4,14.6,NaN,07/01/2012,06/30/2015
4,10001,SOUTHEAST ALABAMA MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,HOUSTON,3347938701,Pneumonia (PN) 30-Day Mortality Rate,MORT_30_PN,No Different than the National Rate,599,15.5,13.0,18.5,NaN,07/01/2012,06/30/2015

In [8]:
timely_effective_care = pd.read_csv("Timely and Effective Care - Hospital.csv")
timely_effective_care.head()

,Provider ID,Hospital Name,Address,City,State,ZIP Code,County Name,Phone Number,Condition,Measure ID,Measure Name,Score,Sample,Footnote,Measure Start Date,Measure End Date
0,10001,SOUTHEAST ALABAMA MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,HOUSTON,3347938701,Heart Attack or Chest Pain,AMI_7a,Fibrinolytic Therapy Received Within 30 Minute...,Not Available,Not Available,7 - No cases met the criteria for this measure.,01/01/2015,12/31/2015
1,10001,SOUTHEAST ALABAMA MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,HOUSTON,3347938701,Heart Attack or Chest Pain,AMI_8a,Primary PCI Received Within 90 Minutes of Hosp...,92,24,3 - Results are based on a shorter time period...,01/01/2015,09/30/2015
2,10001,SOUTHEAST ALABAMA MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,HOUSTON,3347938701,Children's Asthma,CAC_3,Home Management Plan of Care Document,Not Available,Not Available,5 - Results are not available for this reporti...,01/01/2015,12/31/2015
3,10001,SOUTHEAST ALABAMA MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,HOUSTON,3347938701,Emergency Department,ED_1b,ED1,269,535,2 - Data submitted were based on a sample of c...,01/01/2015,12/31/2015
4,10001,SOUTHEAST ALABAMA MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,HOUSTON,3347938701,Emergency Department,ED_2b,ED2,68,535,2 - Data submitted were based on a sample of c...,01/01/2015,12/31/2015

In [9]:
hcaps = pd.read_csv("HCAHPS - Hospital.csv", encoding = "ISO-8859-1")
hcaps.head()

,Provider ID,Hospital Name,Address,City,State,ZIP Code,County Name,Phone Number,HCAHPS Measure ID,HCAHPS Question,...,Patient Survey Star Rating Footnote,HCAHPS Answer Percent,HCAHPS Answer Percent Footnote,HCAHPS Linear Mean Value,Number of Completed Surveys,Number of Completed Surveys Footnote,Survey Response Rate Percent,Survey Response Rate Percent Footnote,Measure Start Date,Measure End Date
0,10001,SOUTHEAST ALABAMA MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,HOUSTON,3347938701,H_STAR_RATING,Summary star rating,...,NaN,Not Applicable,NaN,Not Applicable,1194,NaN,27,NaN,01/01/2015,12/31/2015
1,10001,SOUTHEAST ALABAMA MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,HOUSTON,3347938701,H_CLEAN_HSP_A_P,Patients who reported that their room and bath...,...,NaN,66,NaN,Not Applicable,1194,NaN,27,NaN,01/01/2015,12/31/2015
2,10001,SOUTHEAST ALABAMA MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,HOUSTON,3347938701,H_CLEAN_HSP_SN_P,Patients who reported that their room and bath...,...,NaN,12,NaN,Not Applicable,1194,NaN,27,NaN,01/01/2015,12/31/2015
3,10001,SOUTHEAST ALABAMA MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,HOUSTON,3347938701,H_CLEAN_HSP_U_P,Patients who reported that their room and bath...,...,NaN,22,NaN,Not Applicable,1194,NaN,27,NaN,01/01/2015,12/31/2015
4,10001,SOUTHEAST ALABAMA MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,HOUSTON,3347938701,H_CLEAN_LINEAR_SCORE,Cleanliness - linear mean score,...,NaN,Not Applicable,NaN,84,1194,NaN,27,NaN,01/01/2015,12/31/2015

In [10]:
complications = pd.read_csv("Complications - Hospital.csv")
complications.head()

,Provider ID,Hospital Name,Address,City,State,ZIP Code,County Name,Phone Number,Measure Name,Measure ID,Compared to National,Denominator,Score,Lower Estimate,Higher Estimate,Footnote,Measure Start Date,Measure End Date
0,10001,SOUTHEAST ALABAMA MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,HOUSTON,3347938701,Rate of complications for hip/knee replacement...,COMP_HIP_KNEE,No Different than the National Rate,331,3.8,2.6,5.5,NaN,04/01/2012,03/31/2015
1,10001,SOUTHEAST ALABAMA MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,HOUSTON,3347938701,Serious blood clots after surgery,PSI_12_POSTOP_PULMEMB_DVT,No Different than the National Rate,4549,3.32,1.25,5.38,NaN,07/01/2013,06/30/2015
2,10001,SOUTHEAST ALABAMA MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,HOUSTON,3347938701,Blood stream infection after surgery,PSI_13_POST_SEPSIS,No Different than the National Rate,578,5.72,0.00,11.48,NaN,07/01/2013,06/30/2015
3,10001,SOUTHEAST ALABAMA MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,HOUSTON,3347938701,A wound that splits open after surgery on the...,PSI_14_POSTOP_DEHIS,No Different than the National Rate,445,2.72,0.65,4.79,NaN,07/01/2013,06/30/2015
4,10001,SOUTHEAST ALABAMA MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,HOUSTON,3347938701,Accidental cuts and tears from medical treatment,PSI_15_ACC_LAC,No Different than the National Rate,16429,1.35,0.76,1.95,NaN,07/01/2013,06/30/2015

In [11]:
hospitals_infections.isnull().sum()

Provider ID                  0
Hospital Name                0
Address                      0
City                         0
State                        0
ZIP Code                     0
County Name                720
Phone Number                 0
Measure Name                 0
Measure ID                   0
Compared to National    192720
Score                        0
Footnote                127891
Measure Start Date           0
Measure End Date             0
dtype: int64

In [12]:
outpatient_imaging.isnull().sum()

Provider ID               0
Hospital Name             0
Address                   0
City                      0
State                     0
ZIP Code                  0
County Name              90
Phone Number              0
Measure ID                0
Measure Name              0
Score                     0
Footnote              16313
Measure Start Date        0
Measure End Date          0
dtype: int64

In [13]:
readmission.isnull().sum()

Provider ID                 0
Hospital Name               0
Address                     0
City                        0
State                       0
ZIP Code                    0
County Name               210
Phone Number                0
Measure Name                0
Measure ID                  0
Compared to National        0
Denominator                 0
Score                       0
Lower Estimate              0
Higher Estimate             0
Footnote                41710
Measure Start Date          0
Measure End Date            0
dtype: int64

In [14]:
timely_effective_care.isnull().sum()

Provider ID               0
Hospital Name             0
Address                   0
City                      0
State                     0
ZIP Code                  0
County Name             645
Phone Number              0
Condition                 0
Measure ID                0
Measure Name              0
Score                     0
Sample                 4818
Footnote              46989
Measure Start Date        0
Measure End Date          0
dtype: int64

In [15]:
hcaps.isnull().sum()

Provider ID                                   0
Hospital Name                                 0
Address                                       0
City                                          0
State                                         0
ZIP Code                                      0
County Name                                 825
Phone Number                                  0
HCAHPS Measure ID                             0
HCAHPS Question                               0
HCAHPS Answer Description                     0
Patient Survey Star Rating                    0
Patient Survey Star Rating Footnote      249270
HCAHPS Answer Percent                         0
HCAHPS Answer Percent Footnote           220958
HCAHPS Linear Mean Value                      0
Number of Completed Surveys                   0
Number of Completed Surveys Footnote     233255
Survey Response Rate Percent                  0
Survey Response Rate Percent Footnote    189255
Measure Start Date                            0
Measure End Date                              0
dtype: int64

In [16]:
complications.isnull().sum()

Provider ID                 0
Hospital Name               0
Address                     0
City                        0
State                       0
ZIP Code                    0
County Name               165
Phone Number                0
Measure Name                0
Measure ID                  0
Compared to National        0
Denominator                 0
Score                       0
Lower Estimate              0
Higher Estimate             0
Footnote                31124
Measure Start Date          0
Measure End Date            0
dtype: int64

In [17]:
# summing up the missing values (column-wise)
round(100*(hospitals_infections.isnull().sum()/len(hospitals_infections.index)), 2)

Provider ID              0.00
Hospital Name            0.00
Address                  0.00
City                     0.00
State                    0.00
ZIP Code                 0.00
County Name              0.31
Phone Number             0.00
Measure Name             0.00
Measure ID               0.00
Compared to National    83.33
Score                    0.00
Footnote                55.30
Measure Start Date       0.00
Measure End Date         0.00
dtype: float64

In [18]:
#dropping columns with more than 50% missing data hospitals_infections

hospitals_infections = hospitals_infections.drop('Compared to National', axis=1)
hospitals_infections = hospitals_infections.drop('Footnote', axis=1)


round(100*(hospitals_infections.isnull().sum()/len(hospitals_infections.index)), 2)

Provider ID           0.00
Hospital Name         0.00
Address               0.00
City                  0.00
State                 0.00
ZIP Code              0.00
County Name           0.31
Phone Number          0.00
Measure Name          0.00
Measure ID            0.00
Score                 0.00
Measure Start Date    0.00
Measure End Date      0.00
dtype: float64

In [19]:
#outpatient_imaging
round(100*(outpatient_imaging.isnull().sum()/len(outpatient_imaging.index)), 2)

Provider ID            0.00
Hospital Name          0.00
Address                0.00
City                   0.00
State                  0.00
ZIP Code               0.00
County Name            0.31
Phone Number           0.00
Measure ID             0.00
Measure Name           0.00
Score                  0.00
Footnote              56.43
Measure Start Date     0.00
Measure End Date       0.00
dtype: float64

In [20]:
#dropping missing values outpatient_imaging

outpatient_imaging = outpatient_imaging.drop('Footnote', axis=1)


round(100*(outpatient_imaging.isnull().sum()/len(outpatient_imaging.index)), 2)

Provider ID           0.00
Hospital Name         0.00
Address               0.00
City                  0.00
State                 0.00
ZIP Code              0.00
County Name           0.31
Phone Number          0.00
Measure ID            0.00
Measure Name          0.00
Score                 0.00
Measure Start Date    0.00
Measure End Date      0.00
dtype: float64

In [21]:
#readmission
round(100*(readmission.isnull().sum()/len(readmission.index)), 2)

Provider ID              0.00
Hospital Name            0.00
Address                  0.00
City                     0.00
State                    0.00
ZIP Code                 0.00
County Name              0.31
Phone Number             0.00
Measure Name             0.00
Measure ID               0.00
Compared to National     0.00
Denominator              0.00
Score                    0.00
Lower Estimate           0.00
Higher Estimate          0.00
Footnote                61.84
Measure Start Date       0.00
Measure End Date         0.00
dtype: float64

In [22]:
#dropping missing values readmission

readmission = readmission.drop('Footnote', axis=1)


round(100*(readmission.isnull().sum()/len(readmission.index)), 2)

Provider ID             0.00
Hospital Name           0.00
Address                 0.00
City                    0.00
State                   0.00
ZIP Code                0.00
County Name             0.31
Phone Number            0.00
Measure Name            0.00
Measure ID              0.00
Compared to National    0.00
Denominator             0.00
Score                   0.00
Lower Estimate          0.00
Higher Estimate         0.00
Measure Start Date      0.00
Measure End Date        0.00
dtype: float64

In [23]:
#complications
round(100*(complications.isnull().sum()/len(complications.index)), 2)

Provider ID              0.00
Hospital Name            0.00
Address                  0.00
City                     0.00
State                    0.00
ZIP Code                 0.00
County Name              0.31
Phone Number             0.00
Measure Name             0.00
Measure ID               0.00
Compared to National     0.00
Denominator              0.00
Score                    0.00
Lower Estimate           0.00
Higher Estimate          0.00
Footnote                58.73
Measure Start Date       0.00
Measure End Date         0.00
dtype: float64

In [24]:
#removing missing values for complications

complications = complications.drop('Footnote', axis=1)


round(100*(complications.isnull().sum()/len(complications.index)), 2)

Provider ID             0.00
Hospital Name           0.00
Address                 0.00
City                    0.00
State                   0.00
ZIP Code                0.00
County Name             0.31
Phone Number            0.00
Measure Name            0.00
Measure ID              0.00
Compared to National    0.00
Denominator             0.00
Score                   0.00
Lower Estimate          0.00
Higher Estimate         0.00
Measure Start Date      0.00
Measure End Date        0.00
dtype: float64

In [25]:
#timely_effective_care
round(100*(timely_effective_care.isnull().sum()/len(timely_effective_care.index)), 2)

Provider ID            0.00
Hospital Name          0.00
Address                0.00
City                   0.00
State                  0.00
ZIP Code               0.00
County Name            0.31
Phone Number           0.00
Condition              0.00
Measure ID             0.00
Measure Name           0.00
Score                  0.00
Sample                 2.33
Footnote              22.68
Measure Start Date     0.00
Measure End Date       0.00
dtype: float64

In [26]:
#removing missing values for timely_effective_care

timely_effective_care = timely_effective_care.drop('Footnote', axis=1)


round(100*(timely_effective_care.isnull().sum()/len(timely_effective_care.index)), 2)

Provider ID           0.00
Hospital Name         0.00
Address               0.00
City                  0.00
State                 0.00
ZIP Code              0.00
County Name           0.31
Phone Number          0.00
Condition             0.00
Measure ID            0.00
Measure Name          0.00
Score                 0.00
Sample                2.33
Measure Start Date    0.00
Measure End Date      0.00
dtype: float64

In [27]:
#hcaps
round(100*(hcaps.isnull().sum()/len(hcaps.index)), 2)

Provider ID                               0.00
Hospital Name                             0.00
Address                                   0.00
City                                      0.00
State                                     0.00
ZIP Code                                  0.00
County Name                               0.31
Phone Number                              0.00
HCAHPS Measure ID                         0.00
HCAHPS Question                           0.00
HCAHPS Answer Description                 0.00
Patient Survey Star Rating                0.00
Patient Survey Star Rating Footnote      94.07
HCAHPS Answer Percent                     0.00
HCAHPS Answer Percent Footnote           83.38
HCAHPS Linear Mean Value                  0.00
Number of Completed Surveys               0.00
Number of Completed Surveys Footnote     88.02
Survey Response Rate Percent              0.00
Survey Response Rate Percent Footnote    71.42
Measure Start Date                        0.00
Measure End Date                          0.00
dtype: float64

In [28]:
#removing missing values for hcaps

hcaps = hcaps.drop('Patient Survey Star Rating Footnote', axis=1)
hcaps = hcaps.drop('HCAHPS Answer Percent Footnote', axis=1)
hcaps = hcaps.drop('Number of Completed Surveys Footnote', axis=1)
hcaps = hcaps.drop('Survey Response Rate Percent Footnote', axis=1)


round(100*(hcaps.isnull().sum()/len(hcaps.index)), 2)

Provider ID                     0.00
Hospital Name                   0.00
Address                         0.00
City                            0.00
State                           0.00
ZIP Code                        0.00
County Name                     0.31
Phone Number                    0.00
HCAHPS Measure ID               0.00
HCAHPS Question                 0.00
HCAHPS Answer Description       0.00
Patient Survey Star Rating      0.00
HCAHPS Answer Percent           0.00
HCAHPS Linear Mean Value        0.00
Number of Completed Surveys     0.00
Survey Response Rate Percent    0.00
Measure Start Date              0.00
Measure End Date                0.00
dtype: float64

In [30]:
# Merging the dataframes one by one
df_1 = pd.merge(hospitals_infections, outpatient_imaging, how='inner', on='Provider ID')

In [31]:

df_2 = pd.merge(df_1, complications, how='inner', on='Provider ID')

In [ ]:
df_3 = pd.merge(df_2 , outpatient_imaging, how='inner', on='Provider ID')

In [ ]:
master_df = pd.merge(df_3 , readmission, how='inner', on='Provider ID')